version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.0
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-27-158.compute-1.amazonaws.com
            port: '5432'
            database: deo1ehvj1qjtg5
            ssl: true
            user: dynxyrfhkopicl
            password: eeb269496ba0f833bc2a0e94e12b40c49acbd2a9504f0a3de6eacbedd1829673
            migrations: true